### ISSUE TITLE
fermeture et enregistrement éélments projets

### ISSUE THREAD

**Issue by marcisenmann** [cbn-alpin/gefiproj-webapp#1]
Salut !
Après la saisie de financements ou recettes pour un projet, un petit bouton d'action Enregistrer et fermeture serait utile :
http://149.202.162.89:8081/projet/13

à +
Marc

**Comment by manu0005** [comment]
Bonjour Marc,
L'enregistrement de l'action (ajout/modification/suppression) est immédiat en BDD ; après validation. Du coup, désolé mais je ne comprends pas ta proposition.
Cordialement.

**Comment by marcisenmann** [comment]
Salut,
Oui en effet, ma proposition peut être annulée. Si l'enregistrement immédiat des valeurs dans toutes les cases rend une action d'enregistrement inutile, une action de fermeture du projet pour revenir à l'écran d'accueil peut être utile mais pas indispensable, si l'utilisateur comprend que fermer un projet revient à activer directement Accueil. 
Bonne journée.

**Comment by manu0005** [comment]
Bonjour Marc,
Ce n'est pas tout à fait cela : 
- oui l'enregistrement est immédiat (si validé)
- cependant, nous ne fermons pas le projet, puisque plusieurs modifications sont possibles/envisageables. Pour revenir sur la page d'accueil, un bouton existe dans le menu.
Si tu le souhaites, nous pourrons en discuter via Zoom (ou autre), aujourd'hui ou plus tard.

Bien cordialement.

**Comment by marcisenmann** [comment]
merci pour tes précisions, Manu. Je ne vois pas le bouton dont tu parles. On peut se faire un zoom demain ou un peu plus tard, comme cela cela me laissera un peu plus de temps pour regarder encore les fenêtres de saisies liées aux projet. Très bonne journée à toi.

**Comment by manu0005** [comment]
Je te propose 9h demain, si cela te convient. Cependant, je serais peut-être amené à repousser à l'après-midi, en fonction de mes contraintes.
Heure : 26 janv. 2021 09:00 Paris

Participer à la réunion Zoom
https://univ-grenoble-alpes-fr.zoom.us/j/91565523647?pwd=MmZGZ3VON2JDbENrUGhmOXBEWnhNUT09

ID de réunion : 915 6552 3647
Code secret : 215322
Une seule touche sur l’appareil mobile
+33170950350,,91565523647# France
+33186995831,,91565523647# France

Composez un numéro en fonction de votre emplacement
        +33 1 7095 0350 France
        +33 1 8699 5831 France
        +33 1 7037 2246 France
        +33 1 7037 9729 France
        +33 1 7095 0103 France
ID de réunion : 915 6552 3647
Trouvez votre numéro local : https://univ-grenoble-alpes-fr.zoom.us/u/adQd9HIJbz

Participer à l’aide d’un protocole SIP
91565523647@zoomcrc.com

Participer à l’aide d’un protocole H.323
162.255.37.11 (États-Unis (Ouest))
162.255.36.11 (États-Unis (Est))
213.19.144.110 (Amsterdam Pays-Bas)
213.244.140.110 (Allemagne)
Code secret : 215322
ID de réunion : 915 6552 3647

**Comment by marcisenmann** [comment]
Ok Manu, Ca me va pour demain 9h avec la flexibilité qui s'impose en cas de contraintes pro. Pas de problème.

**Comment by manu0005** [comment]
Suite à discussion (ce matin), Marc valide notre gestion des éléments (détails, financements, recettes et affectations) des projets. 
Du coup, je clôture l''issue'.
