### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by manu0005** [cbn-alpin/gefiproj-webapp#4]
Marc,
Je sais que la pagination n'est pas demandée (voir même, est non désirée) et certainement pas nécessaire partout, ni tout de suite. Cependant, à terme, cela devrait être utile pour certains affichages, je suppose : les utilisateurs (déjà 41 personnes prévues), l'historiques des modifications, les projets si affichage des clôturés, etc. C'est éléments (et d'autres) vont plus ou moins rapidement grossir, sauf à prévoir une purge ou un archivage.

Pour février c'est certainement un peu tard, mais je vous invite à y réfléchir pour la suite. :)
Cordialement.

**Comment by marcisenmann** [comment]
Salut, Si pagination = historisation, oui je te confirme que cela n'est pas une priorité pour nous. Sauf pour les 2 champs commentaires, où il serait bien de garder l’historique des commentaires en les horodatant. Mais c'est mon avis à moi. Nous verrons à l'utilisation nous ajouterons ce type de fonction un peu plus tard. A demain.
Marc

**Comment by manu0005** [comment]
Non, je parle de la gestion des pages d'affichage ('infinite scroll', boutons de navigation, etc.), pour ne pas avoir des tableaux trop long :
![image](https://user-images.githubusercontent.com/49067444/106459573-550f4900-6492-11eb-8a8b-383f89b05334.png)
[Des éléments de réflexion](https://www.codeur.com/blog/alternatives-infinite-scroll/)
:)

**Comment by manu0005** [comment]
Lors de la réunion du 2/2, j'ai évoqué cet élément. Jean-Pascal nous a indiqué que cela serait intégré en fonction du besoin ; lors de la maintenance de l'application.
Du coup, je clôture cette issue qui n'a que pour vocation que d'informer CBNA.
