### ISSUE TITLE
fenêtre Financeurs

### ISSUE THREAD

**Issue by marcisenmann** [cbn-alpin/gefiproj-webapp#5]
- tableau à élargir pour mieux lire le nom complet du financeur libellé dans [ref de l'arrêté attributif]. 
[Nom] = "Sigle" ou "libéllé simplifié" du financeur
[Ref de l'arrêté attributif] = Libellé du financeur tel que écrit dans l'arrêt attributif

**Comment by marcisenmann** [comment]
- importer éventuellement la liste actuelle des financeurs utilisés actuellement par bertrand
[Tableau des financeurs.xlsx](https://github.com/cbn-alpin/gefiproj-webapp/files/5942081/Tableau.des.financeurs.xlsx)
rs utilisés par le CBNA [(tableau financeur)

**Comment by manu0005** [comment]
Nous allons tenir compte de ces remarques et préparer une injection (SQL) des financeurs fournis.

**Comment by manu0005** [comment]
Les financeurs ont été injectés. :)

**Comment by marcisenmann** [comment]
Parfait 👍. Injection basique et utile....

**Comment by manu0005** [comment]
Merci, à votre service :)

**Comment by manu0005** [comment]
Le tableau a été agrandi (pas encore poussé sur OVH) :
![image](https://user-images.githubusercontent.com/49067444/107624790-a7ebbc00-6c5b-11eb-8990-114360fea325.png)

Pour l'injection des utilisateurs, un script SQL est disponible sur le Drive, le notre et ici :
![image](https://user-images.githubusercontent.com/49067444/107625226-4d069480-6c5c-11eb-8c89-5a0d781ba0d4.png)
Je vais attendre demain pour mettre à jour tous les scripts.

Si cela te convient, je pense que cette issue peut-être clôturée.

**Comment by marcisenmann** [comment]
Très bien 👍.
